Backport firmware & OS Upgrade to bionic
pop-os/gnome-control-center pull request #12
Opened 2019-03-18 22:50 UTC by mmstick

Adds the firmware & OS upgrade patches developed in the cosmic branch.

2019-04-05 00:09 UTC, brs17 requested changes
Clicking away from the `About` tab in gnome-control-center crashes(Seg faults) the application. 

Log message when selecting the `Details` tab:
```
(gnome-control-center:3354): info-cc-panel-WARNING **: 18:05:46.935: failed to call ReleaseCheck on PopUpgrade: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.system76.PopUpgrade was not provided by any .service files
```
Then, `Segmentation fault (core dumped)`

2019-04-05 00:20 UTC, brs17 commented
Highlighted underneath "OS Upgrade and Refresh": "No upgrades available" there seems to be a second highlightable widget that in the following screenshot I have highlighted. 
![Screenshot from 2019-04-04 18-09-40](https://user-images.githubusercontent.com/7460774/55596309-1fb63a80-5705-11e9-96e2-bd8c22630c64.png)

2019-04-05 00:21 UTC, brs17 commented
When no upgrades are available, I have no idea what the `Unlock` /`Lock` is supposed to do.

2019-04-05 00:44 UTC, brs17 commented
If this is supposed to replace the system76-firmware application, shouldn't we list the installed version of the BIOS/EC/EC2/ME regardless of an update being available? The system76-firmware application also shows the changelog...I'm not sure if this should be listed on the About page (in its current layout), but should probably be provided somewhere.

2019-04-05 00:50 UTC, brs17 commented on debian/patches/s76_firmware.patch
> ++    label = _("No Updates Available");
`U` and `A` should be lowercase:
`No updates available`

2019-04-05 00:57 UTC, mmstick commented
We could list them, if that's desired. The pop-upgrade daemon does have to be installed for the os upgrade feature to work. Soon there will be a "Refresh OS" button in there to give that unlock button more of a purpose. Segfault is likely due to a bad instance of `free ()`.

2019-04-05 13:31 UTC, brs17 commented
@mmstick My thought is that the changelog provides the user an understanding for what an update contains. I would think this will help convince users of the importance and the need to run up to date firmware.

2019-04-05 13:53 UTC, WatchMkr commented
The change log description of the firmware update is on the confirmation page. Please review the original design for copy as well.

2019-04-05 19:17 UTC, WatchMkr commented
@mmstick what does the unlock switch do for the "Refresh OS" option?

2019-04-05 19:26 UTC, mmstick commented
None of the buttons in the panel can be clicked until the panel is unlocked. Same behavior as in the "Users" panel, which requires the panel to be unlocked to make changes to user accounts.

2019-04-09 01:17 UTC, brs17 commented
The buttons look cut off on the bottom of the button:
![Screenshot from 2019-04-08 18-33-57](https://user-images.githubusercontent.com/7460774/55766261-29a3aa80-5a31-11e9-814a-390dd8c5edc2.png)

I noticed that the object containing the text of what is happening changes size based on the content within:
![Screenshot from 2019-04-08 18-45-44](https://user-images.githubusercontent.com/7460774/55766280-417b2e80-5a31-11e9-8cf4-689837d6520c.png)
![Screenshot from 2019-04-08 18-45-54](https://user-images.githubusercontent.com/7460774/55766281-417b2e80-5a31-11e9-9d9b-4f35c5da5110.png)

After the updates were downloaded, I had the "About" page which said that a reboot was required. I tried clicking on that label, and gnome-control-center crashed. 

I then rebooted and was brought into a 18.04 recovery partition. Getting back to the user partition, I was prompted in gnome-control-center that an upgrade was available.

2019-04-09 01:53 UTC, brs17 commented
- I saw gnome-control-center crash after finishing with "Upgrade from 18.04->18.10".

- The recovery partition update works, although the About page still says an update is available.

2019-04-09 02:28 UTC, mmstick commented
There are some segfaults at the end. Once you're in the recovery partition, it is possible to install the installer PR to try out the upgrade from the recovery partition. The upgrade button in GCC is doing a recovery upgrade when it detects that a recovery partition exists, even if the recovery partition is not mounted at the time of the upgrade attempt.

2019-04-09 06:40 UTC, WatchMkr commented
We won’t want verbose messages here. Please see copy for the feature here:

https://github.com/pop-os/gnome-control-center/issues/8

I believe it covers all copy scenarios for the feature (at least in the Gnome UI).

2019-04-09 16:15 UTC, mmstick commented
I'll remove handling of the specific package events for GCC. These events are mainly for the CLI frontend.

2019-05-02 15:12 UTC, brs17 commented
- With the latest changes, I notice that it is taking significantly longer to select/load the "Details" page than without the patch.

- While a mockup has not been provided of how to display the firmware versions, I would think we should not provide the firmware versions in textboxes as I see in the following screenshot, but rather labels(I'm assuming) like the information provided higher up on the page. I think we should also strive to keep similar formatting. I notice that `bios`, `ec, `ec2`, `me` are all bolded while titles like `Computer`, `Model`, `Memory`, are not. Also capitalization should be consistent.

![firmware](https://user-images.githubusercontent.com/7460774/57085012-9ae51f00-6cb8-11e9-9d03-847fb88c5051.png)

- I also noticed that the version for the M.E. from the screenshot (11.8.50.3425) is not what is shown in the firmware daemon nor the BIOS (disabled/0.0.0.0)

2019-05-02 15:19 UTC, brs17 commented
Selecting "Reflash" caused a segfault in gnome-control-center.

Appropriate journald logs:

[logs.log](https://github.com/pop-os/gnome-control-center/files/3138724/logs.log)

2019-05-02 16:57 UTC, brs17 commented
I reverted the firmware to an older version so that I could test upgrading firmware. I did not see firmware versions, nor the ability to upgrade.

![Screenshot from 2019-05-02 10-31-37](https://user-images.githubusercontent.com/7460774/57091290-15686b80-6cc6-11e9-9f58-43b2c7e29071.png)

I then rebooted and got the information I was expecting.

2019-05-02 17:08 UTC, brs17 commented
The firmware update popup is missing the information regarding the new firmware available.

I am also thinking the `Reboot and Install` button should probably be an affirmative color as we want users to upgrade to the latest firmware, but that is definitely not my area of "expertise" perhaps @isantop or @WatchMkr have a thought about it.

![Screenshot from 2019-05-02 10-58-44](https://user-images.githubusercontent.com/7460774/57092786-67f75700-6cc9-11e9-8b14-9fe654834c0b.png)

2019-05-02 17:16 UTC, brs17 commented
Upon pressing the `Reboot and Install` button, gnome-control-center closed. 

Log line from journald from time of crash

```
May 02 11:09:59 pop-os kernel: traps: gnome-control-c[2106] general protection ip:7fa8fed476a6 sp:7fffd561c020 error:0 in libgio-2.0.so.0.5600.4[7fa8fec7a000+195000]
```

2019-05-02 17:57 UTC, brs17 commented
On a BIOS system, gnome-control-center segfaults and I am unable to open the application.

2019-05-02 21:05 UTC, mmstick commented
The crashes should be fixed now

2019-05-06 18:54 UTC, mmstick commented
Updated screenshots. Almost finished with this PR

2019-06-17 17:10 UTC, brs17 commented
I think the `Refresh OS` button should be white instead of green as it is not something that should be recommended like an upgrade.

2019-06-17 17:11 UTC, brs17 commented
I notice that the M.E. version is listed but the M.E. is disabled so it should say `disabled`. In the firmware updater tool the m.e. is listed as disabled.

2019-06-17 21:42 UTC, brs17 commented
When selecting the `Recovery update available` this should update the recovery partition to the latest iso/image of the current OS installed.

When selecting `Upgrade from 1804 to 19.04`, I am first prompted to upgrade the recovery partition. Since this upgrade would turn the recovery partition into a 19.04 image, I am not sure we want to prompt the user as this is a required part of upgrading the system.

When the download/upgrade process is being shown in GCC, the `Refresh OS` option says `Release upgrade in progress - please wait`. If possible I would say that this option should be hidden during the installation process and only shown after the installation is complete.

I also noticed an odd issue with the inability to resize the About page. @mmstick seemed to be aware of what the fix should be.

2019-06-19 13:27 UTC, brs17 commented
UPDATE: After a discussion with the entire team, the firmware information is going to be re-implemented in a library that can then be added to gnome-control-center or used in the Ubuntu offering.

2019-06-26 19:35 UTC, mmstick commented
Finished the firmware widget library implementation. Now working on a library implementation of the upgrade portion. Closing this in the meantime, as the two libraries will be in two different pull requests.

2019-06-26 19:35 UTC, closed without merging